## 7.7. Exceptions specifications and noexcept keyword.
Есть готовые классы для исключений:
```cpp
#include <exception>
/*
std::runtime_error
std::logic_error
std::out_of_range
std::bad_alloc // не удалось выделить память
std::bad_cast // cast не удался
*/

int main() {
    std::runtime_error re("Hello\n");

    std::cout << re.what(); // Hello

    // обычно пишут, например throw std::out_of_range("Something");
}
```
но в промышленной разработке обычно есть свои типы под исключения, поэтому эта штука редко используется.

Важно понимать, что `std::runtime_error` - это не тот же RT, что и ошибка в контесте. Например, в контесте деление на 0 - RT, но в C++ это не исключение.

**Спецификация исключений** - указание в сигнатуре функции типов исключений, которые могут из нее `throw`. В обычном виде это не используется, т.к. в этом мало смысла. Но позже ввели *бинарную* спецификацию исключений - либо сама функция кидает исключение (или функции, которая она вызывает), либо нет.
```cpp
void f() noexcept {
    ...
}
```
пишется после `const`, `override`, `final`. 

Однако если написать:
```cpp
void f() noexcept {
    throw std::runtime_error("Hi!");
}
```
то оно скомпилится, т.к. на этапе компиляции долго это проверять (или ещё почему-то). 

А вот так:
```cpp
void g() {
    ...
}

void f() noexcept {
    g();
}
```
даже warning'а не будет. 

Если из `noexcept` функции кидается исключение, то сразу будет `terminate` (проигнорируются `catch`'и).

Обычно на `noexcept` забивают, то есть не пишут (хотя зависит от codestyle).

Можно писать вот так:
```cpp
// true, если f помечена как noexcept. Иначе false.
std::cout << noexcept(f());
```
вычисляется на этапе компиляции.

Еще можно так:
```cpp
template<int N>
void f() noexcept(N > 5) {
    ...
}
```
И вот так:
```cpp
void f() noexcept(noexcept(g())) {
    ...
}
```

## 7.8. Function try block.
Можно писать вот так:
```cpp
int f() noexcept try {
    ...
} catch (...) {
    // при этом в catch нужно написать return какой-то int.
    ...
}
```
это нужно на случай возникновения исключений в списке инициализации конструктора.
Например:
```cpp
struct S
    std::string s;
    S(const std::string& s) noexcept try: s(s) {
        ...
    } catch(...) {
        ...
    }
};
```
## 7.9. Arguments against using exceptions
Exceptions сильно усложняют чтение кода.

google style guide призывает не использовать exceptions.

**weak exception-safety** - если какие-то объекты кидают исключение внутри нашего метода, то наш класс должен остаться в валидном состоянии и послать исключение дальше.

**strong exception-safety** - если какие-то объекты кидают исключение внутри нашего метода, то наш класс должен остаться в состоянии, в каком он был до вызова метода, и послать исключение дальше.

Из-за того, что стандартные контейнеры стараются поддерживать strong exception-safety, их реализация сложная.

# VIII. Containers.
## 8.1. General information about containers.
Sequence containers:
* vector, deque
* list, forward_list

Associative containers:
* map, set
* unordered_map, unordered_set

### vector
* push_back, pop_back - amortized O(1)
* [], at - guaranteed O(1)

Сконструировать от переданного параметра внутри самого метода:
```cpp
//std::vector<S> v;
v.emplace_back(0);
```
### deque
* push_back, pop_back, push_front, pop_front - amortized O(1)
* [], at - guaranteed O(1)

В отличие от `vector`, не требует конструктора копирования.
### list
* push_back, pop_back, push_front, pop_front - guaranteed O(1)
* insert, erase - guaranteed O(1)

На каждый `push_back` идет обращение к оператору `new`, поэтому работает медленно.

На каждый эл-т хранит еще два указателя, поэтому требует много памяти.
### forward_list
* push_front, pop_front - guaranteed O(1)
* insert, erase - guaranteed O(1)
### map, set
* (map only) [], at - guaranteed O(log n)
* insert, erase - guaranteed O(log n)
### unordered_map, unordered_set
* (map only) [], at - expected O(1)
* insert, erase - expected O(1)

есть реализации быстрее, чем встроенные. Но встроенные стараются выполнять требование strong exception-safety и поддерживают итераторы.
## 8.2. Basics of iterators.
```cpp
int main() {
    std::list<int> a = {1, 2, 3};
    for (std::list<int>::iterator it = a.begin(); it != a.end(); ++it) {
        std::cout << *it;
    }
}
```
Это равносильно коду выше:
```cpp
int main() {
    std::list<int> a = {1, 2, 3};
    for (int x : a) {
        std::cout << x;
    }
}
```
такое можно писать для любого класса, поддерживающего методы `begin` и `end`.

получить константный итератор: `a.cbegin()`, `a.cend()`.

**Iterators invalidation** - когда старые итераторы становятся невалидными после изменений контейнера. Пример:
```cpp
std::vector<int> v(1);
auto it = v.begin();
for (int i = 0; i < 100; ++i) {
    v.push_back(i);
}
*it = 100;
```
это seg fault. При этом если заменить `vector` на `deque`, то всё будет ок (он не перекладывает эл-ты).